version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass redis
    ports:
        - '6379:6379'
volumes:                               
  redisdb:
    driver: local